#e58593d1-8f78-49da-aeeb-d837ec8b6768
language: node_js
node_js:
  - "9"

env:
  - NODE_ENV=ci

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      services:
        - postgresql
      before_script:
        - psql -c 'create database toolbelt;' -U postgres
      script:
        - yarn run lint
        - yarn run flow
        - yarn run test
    - stage: coverage
      services:
        - postgresql
      before_script:
        - psql -c 'create database toolbelt;' -U postgres
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    - stage: deploy
      script: yarn build
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          branch: master
  

branches:
  only:
  - master
