language: node_js
node_js:
  - "9"

env:
  - NODE_ENV=ci

services:
  - postgresql

before_script:
  - psql -c 'create database toolbelt;' -U postgres

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      script:
        - yarn run lint
        - yarn run flow
        - yarn run test
    - stage: build
      script:
        - yarn run build
branches:
  only:
  - master
