// flow-typed signature: 1c374fb19190c1ae9cc48d9bb4beef8d
// flow-typed version: <<STUB>>/exif-reader_v^1.0.2/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exif-reader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'exif-reader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'exif-reader/tags' {
  declare module.exports: any;
}

declare module 'exif-reader/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'exif-reader/index' {
  declare module.exports: $Exports<'exif-reader'>;
}
declare module 'exif-reader/index.js' {
  declare module.exports: $Exports<'exif-reader'>;
}
declare module 'exif-reader/tags.js' {
  declare module.exports: $Exports<'exif-reader/tags'>;
}
declare module 'exif-reader/test/index.js' {
  declare module.exports: $Exports<'exif-reader/test/index'>;
}
